# Generated by Django 3.0.5 on 2020-12-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_auto_20201201_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugticket',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bugticket',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bugticket',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=30),
        ),
        migrations.AlterField(
            model_name='bugticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=30),
        ),
        migrations.AlterField(
            model_name='bugticket',
            name='type',
            field=models.CharField(choices=[('Development', 'Development'), ('Testing', 'Testing'), ('Production', 'Production')], max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
